version: '3.8'
services:
  master:
    build: .
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - sfs:/sfs
    command: /spark.sh 0

  worker:
    build: .
    ports:
      - 8080
    command: /spark.sh 1

  driver:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/app
      - sfs:/sfs
    command: /jupyter.sh
volumes:
  sfs:
