version: '3.8'
services:
  master:
    build: .
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - ./src:/src
    command: /spark.sh 0

  worker:
    build: .
    ports:
      - 8080
    command: /spark.sh 1

  driver:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/app
      - ./src:/src
    command: /jupyter.sh
  
  builder:
    image: "hseeberger/scala-sbt:8u222_1.3.5_2.13.1"
    volumes:
    - ./src:/src
    command: tail -F anything

